version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: remember2pack-backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: development
      PORT: 3001
      FRONTEND_URL: http://localhost:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - remember2pack-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:3001
    container_name: remember2pack-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - remember2pack-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  remember2pack-network:
    driver: bridge
